# This workflow will push and update articles on dev.to each time a new
# commit is pushed to the main branch.

name: publish
on:
  push:
    branches: [main]
    paths: ['posts/**/*.md']
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GIT_COMMITTER_EMAIL: itlackey@gmail.com
      GIT_COMMITTER_NAME: itlackey
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 20

    - name: Publish articles on dev.to
      uses: sinedied/publish-devto@v2
      with:
        devto_key: ${{ secrets.DEVTO_TOKEN }}
        github_token: ${{ secrets.GH_TOKEN }}
        files: 'posts/**/*.md'
        branch: main
        conventional_commits: true
